---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tandoor
  namespace: flux-system
spec:
  components:
    - ../../../../components/kopiur
    - ../../../../components/volsync
  targetNamespace: *app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kopiur-repository-tandoor
      namespace: flux-system
    - name: volsync
      namespace: flux-system
  path: "./kubernetes/misc/tandoor/tandoor/app"
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: tandoor
      KOPIUR_SOURCE_PVC: tandoor-miroir
      KOPIUR_SCHEDULE: "7 */6 * * *"
      VOLSYNC_REPOSITORY: s3:http://garage.garage.svc.cluster.local:3900/volsync/tandoor/tandoor
      VOLSYNC_SOURCE_PVC: tandoor-miroir
      VOLSYNC_STORAGE_CLASS: miroir-replicated
      VOLSYNC_VOLUME_SNAPSHOT_CLASS: miroir-snap
      VOLSYNC_CACHE_STORAGE_CLASS: miroir-ephemeral
      VOLSYNC_MOVER_APP_NAME: tandoor
      VOLSYNC_MOVER_APP_INSTANCE: tandoor
      VOLSYNC_SCHEDULE: "7 */6 * * *"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
