---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kopiur
spec:
  interval: 30m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.10.10
  url: oci://ghcr.io/home-operations/charts/kopiur
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopiur
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: kopiur
  driftDetection:
    mode: enabled
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  values:
    installScope: cluster
    image:
      tag: 0.10.10
      digest: sha256:53932cb3084f36f01d47b32a73abb375dd10077f5b1e865d022bb7df9573b0a5
    mover:
      image:
        tag: 0.10.10
        digest: sha256:15d096c8ea2f0e0510b2d686771a45c9dead74ac2aa1354201210635c00c3128
    monitoring:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
        backupStaleAfterSeconds: 21600
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          allowCrossNamespaceImport: true
          folder: Storage
          matchLabels:
            dashboards: grafana
    webhook:
      image:
        tag: 0.10.10
        digest: sha256:58dabec849b472d04c53499c2f6ea060f6c44f7babf8b465670c40fec625d7e5
      failurePolicy: Fail
      serviceMonitor:
        enabled: true
        insecureSkipVerify: true