---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kopiur
spec:
  interval: 30m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.10.10
  url: oci://ghcr.io/home-operations/charts/kopiur
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopiur
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: kopiur
  driftDetection:
    mode: enabled
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  values:
    installScope: cluster
    image:
      tag: 0.10.9
      digest: sha256:8048ef02bf1154d896f91c49fa7d241fc062fbfa64becb2df456bd4f78966a37
    mover:
      image:
        tag: 0.10.9
        digest: sha256:f909a37cb9f6de6dba4a3190e75b0b505c4d61f28005b729bd8e0976fff1c8fd
    monitoring:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
        backupStaleAfterSeconds: 21600
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          allowCrossNamespaceImport: true
          folder: Storage
          matchLabels:
            dashboards: grafana
    webhook:
      image:
        tag: 0.10.9
        digest: sha256:b3bc914480d9e9c9e3c0c9e10208d4155f02216c709cdb782046a2d722ff0a36
      failurePolicy: Fail
      serviceMonitor:
        enabled: true
        insecureSkipVerify: true