---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kopiur
spec:
  interval: 30m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.10.7
  url: oci://ghcr.io/home-operations/charts/kopiur
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopiur
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: kopiur
  driftDetection:
    mode: enabled
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: Skip
    remediation:
      strategy: rollback
      retries: 3
  values:
    installScope: cluster
    image:
      tag: 0.10.7
      digest: sha256:ce50917db136e4f19b480724d5cff7a4e1eeed9431e737aeb7808b2693dcefe5
    mover:
      image:
        tag: 0.10.7
        digest: sha256:b6efbb3dedb88a87bc01f089f5f5e61dc3b306a4003a604c3bf01b1d3c335033
    monitoring:
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
        backupStaleAfterSeconds: 21600
      dashboards:
        enabled: true
        grafanaOperator:
          enabled: true
          allowCrossNamespaceImport: true
          folder: Storage
          matchLabels:
            dashboards: grafana
    webhook:
      image:
        tag: 0.10.7
        digest: sha256:788171c81579946053479fb81c7762564471761c3bdf45721dc6a0eacebfc6fa
      failurePolicy: Fail
      serviceMonitor:
        enabled: true
        insecureSkipVerify: true
