---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name hermes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      data:
        OPENROUTER_API_KEY: "{{ .OPENROUTER_API_KEY }}"
        API_SERVER_KEY: "{{ .API_SERVER_KEY }}"
  dataFrom:
    - extract:
        key: hermes
    - extract:
        key: ai-api-keys
