---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name hermes
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      data:
        AGENTMEMORY_SECRET: "{{ .AGENTMEMORY_SECRET }}"
        API_SERVER_KEY: "{{ .API_SERVER_KEY }}"
        DISCORD_ALLOWED_USERS: "{{ .DISCORD_ALLOWED_USERS }}"
        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        FIRECRAWL_API_KEY: "{{ .TOKEN }}"
        OPENROUTER_API_KEY: "{{ .OPENROUTER_API_KEY }}"
  dataFrom:
    - extract:
        key: hermes
    - extract:
        key: agentmemory
    - extract:
        key: ai-api-keys
    - extract:
        key: firecrawl
