---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
spec:
  target:
    name: immich-secret
    template:
      data:
        # App
        JWT_SECRET: "{{ .IMMICH_SECRET_KEY }}"
        # Database
        DB_URL: 'postgresql://immich:{{ .IMMICH_POSTGRES_PASSWORD }}@pgvector17-rw.databases.svc.cluster.local:5432/immich_db?sslmode=disable'
        DB_HOSTNAME: 'pgvector17-rw.databases.svc.cluster.local'
        DB_PORT: '5432'
        DB_USERNAME: &dbuser immich
        DB_PASSWORD: &dbpass '{{ .IMMICH_POSTGRES_PASSWORD }}'
        DB_DATABASE_NAME: 'immich_db'
        # Postgres init
        INIT_POSTGRES_DBNAME: immich_db
        INIT_POSTGRES_HOST: pgvector17-rw.databases.svc.cluster.local
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
  dataFrom:
  - extract:
      key: immich
    sourceRef:
       storeRef:
         kind: ClusterSecretStore
         name: onepassword-connect
  - extract:
      key: cloudnative-pg
    sourceRef:
       storeRef:
         kind: ClusterSecretStore
         name: onepassword-connect
