---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
spec:
  target:
    name: immich-secret
    template:
      data:
        # App
        JWT_SECRET: "{{ .IMMICH_SECRET_KEY }}"
        # Database
        DB_URL: 'postgresql://{{ .POSTGRES_SUPER_USER }}:{{ .POSTGRES_SUPER_PASS }}@pgvector17.databases.svc.cluster.local:5432/immich_db?sslmode=disable'
        DB_HOSTNAME: 'pgvector17.databases.svc.cluster.local'
        DB_PORT: '5432'
        DB_USERNAME: '{{ .POSTGRES_SUPER_USER }}'
        DB_PASSWORD: '{{ .POSTGRES_SUPER_PASS }}'
        DB_DATABASE_NAME: 'immich_db'
  dataFrom:
  - extract:
      key: immich
    sourceRef:
       storeRef:
         kind: ClusterSecretStore
         name: onepassword-connect
  - extract:
      key: cloudnative-pg
    sourceRef:
       storeRef:
         kind: ClusterSecretStore
         name: onepassword-connect