---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: open-webui-config-miroir
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir-replicated
  resources:
    requests:
      storage: 10Gi
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: open-webui-config-miroir-restore
