---
alertmanager:
  interval: 60s
  servers:
    - name: main
      uri: http://alertmanager-operated.observability.svc.cluster.local:9093
      timeout: 10s
      healthcheck:
        visible: false
        filters:
          alertmanager:
            - alertname=Watchdog
filters:
  default:
    - "@state!=suppressed"
