---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: autobrr
  namespace: flux-system
spec:
  components:
    - ../../../components/kopiur
    - ../../../components/volsync
  targetNamespace: home-media
  commonMetadata:
    labels:
      app.kubernetes.io/name: autobrr
  dependsOn:
    - name: kopiur-repository-home-media
      namespace: flux-system
    - name: volsync
      namespace: flux-system
  path: "./kubernetes/media/autobrr/app"
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: autobrr
      KOPIUR_SOURCE_PVC: autobrr-miroir
      KOPIUR_SCHEDULE: "39 */6 * * *"
      KOPIUR_SUSPEND: "false"
      VOLSYNC_REPOSITORY: s3:http://garage.garage.svc.cluster.local:3900/volsync/home-media/autobrr
      VOLSYNC_SOURCE_PVC: autobrr-miroir
      VOLSYNC_STORAGE_CLASS: miroir-replicated
      VOLSYNC_VOLUME_SNAPSHOT_CLASS: miroir-snap
      VOLSYNC_CACHE_STORAGE_CLASS: miroir-ephemeral
      VOLSYNC_MOVER_APP_NAME: autobrr
      VOLSYNC_MOVER_APP_INSTANCE: autobrr
      VOLSYNC_SCHEDULE: "39 */6 * * *"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
