---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otterwiki-kopiur-replacement
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: miroir-replicated
  resources:
    requests:
      storage: 20Gi
