---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: shelfmark
  namespace: flux-system
spec:
  components:
    - ../../../components/kopiur
    - ../../../components/volsync
  targetNamespace: books
  commonMetadata:
    labels:
      app.kubernetes.io/name: shelfmark
  dependsOn:
    - name: kopiur-repository-books
      namespace: flux-system
    - name: volsync
      namespace: flux-system
  path: "./kubernetes/books/shelfmark/app"
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: shelfmark-config
      KOPIUR_SOURCE_PVC: shelfmark-config-kopiur-replacement
      KOPIUR_SCHEDULE: "33 */6 * * *"
      KOPIUR_SUSPEND: "false"
      VOLSYNC_REPOSITORY: s3:http://garage.garage.svc.cluster.local:3900/volsync/books/shelfmark-config
      VOLSYNC_SOURCE_PVC: shelfmark-config-kopiur-replacement
      VOLSYNC_STORAGE_CLASS: miroir-replicated
      VOLSYNC_VOLUME_SNAPSHOT_CLASS: miroir-snap
      VOLSYNC_CACHE_STORAGE_CLASS: miroir-ephemeral
      VOLSYNC_MOVER_APP_NAME: shelfmark
      VOLSYNC_MOVER_APP_INSTANCE: shelfmark
      VOLSYNC_SCHEDULE: "33 */6 * * *"
      VOLSYNC_COPY_METHOD: Snapshot
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
