---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopiur-pilot-restore
  namespace: flux-system
spec:
  suspend: false
  targetNamespace: books
  path: ./kubernetes/storage/kopiur/restores/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: kopiur-repository-books
      namespace: flux-system
    - name: miroir-config
      namespace: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 30m
  postBuild:
    substitute:
      APP: shelfmark-config
      KOPIUR_RESTORE_CAPACITY: 20Gi
      KOPIUR_RESTORE_SNAPSHOT_ID: 83fa845bef123fdef57a239640819677
