---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app mcp-grafana
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      mcp-grafana:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mcp/grafana
              tag: latest@sha256:9362bcf6aa0e44e61f645b905cec03fb346a946a34a4dafecd7f3e28d3724014
              pullPolicy: Always
            args:
              - "-t"
              - "streamable-http"
              - "--allowed-hosts"
              - "grafana-mcp.${LOCAL_DOMAIN},mcp-grafana.observability.svc.cluster.local:8000"
            env:
              GRAFANA_URL: "http://grafana-service.observability.svc.cluster.local:3000"
            envFrom:
              - secretRef:
                  name: mcp-grafana-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                cpu: 50m
                memory: 128Mi
              limits:
                memory: 256Mi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8000
    route:
      app:
        enabled: true
        annotations:
          gatus.home-operations.com/endpoint: |
            url: https://grafana-mcp.${LOCAL_DOMAIN}/mcp
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
        hostnames:
          - grafana-mcp.${LOCAL_DOMAIN}
        rules:
          - backendRefs:
              - name: *app
                port: 8000
