---
title: Dashboard
favicon: https://raw.githubusercontent.com/auricom/home-ops/main/docs/src/assets/logo.png
background: 
  image: https://www.nasa.gov/wp-content/uploads/2025/05/54470656907-2362dd2f92-o.jpg?auto=format&fit=crop&w=2560&q=80
  opacity: 30
theme: dark
cardBlur: md
color: neutral
headerStyle: clean
layout:
  Calendar:
    tab: Home
    style: column
    icon: mdi-calendar
  Media:
    tab: Home
    style: column
    icon: mdi-play-circle
  Photos:
    tab: Home
    style: row
    columns: 1
    icon: mdi-image-multiple
  Books:
    tab: Home
    style: column
    icon: mdi-book-open-page-variant
    useEqualHeights: true
  AI:
    tab: Home
    style: column
    icon: mdi-robot
    useEqualHeights: true
  Applications:
    tab: Home
    style: row
    columns: 3
    icon: mdi-server
  Downloads:
    tab: Infrastructure
    style: row
    columns: 1
    icon: mdi-download-circle
    useEqualHeights: true
  Storage:
    tab: Infrastructure
    style: row
    columns: 2
    icon: mdi-desktop-tower
    useEqualHeights: true
  Networking:
    tab: Infrastructure
    style: row
    icon: mdi-router-wireless
  Observability:
    tab: Infrastructure
    style: row
    columns: 2
    icon: mdi-chart-line
    useEqualHeights: true
