---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/tuppr.home-operations.com/talosupgrade_v1alpha1.json
apiVersion: tuppr.home-operations.com/v1alpha1
kind: KubernetesUpgrade
metadata:
    name: kubernetes
spec:
    kubernetes:
        # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
        version: v1.37.0
    healthChecks:
        - apiVersion: kopiur.home-operations.com/v1alpha1
          kind: Snapshot
          expr: |-
              status.conditions.filter(c, c.type == "Reconciling").all(c, c.status == "False")
        - apiVersion: kopiur.home-operations.com/v1alpha1
          kind: Restore
          expr: |-
              status.conditions.filter(c, c.type == "Reconciling").all(c, c.status == "False")
        - apiVersion: kopiur.home-operations.com/v1alpha1
          kind: Repository
          expr: |-
              status.conditions.exists(c, c.type == "Ready" && c.status == "True")
        - apiVersion: kopiur.home-operations.com/v1alpha1
          kind: SnapshotPolicy
          expr: |-
              status.conditions.exists(c, c.type == "Ready" && c.status == "True")
        - apiVersion: kopiur.home-operations.com/v1alpha1
          kind: SnapshotSchedule
          expr: |-
              status.conditions.exists(c, c.type == "Ready" && c.status == "True")
        - apiVersion: miroir.home-operations.com/v1alpha1
          kind: MiroirVolume
          expr: |-
              status.phase == 'Ready'
