---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ${APP}-restic
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: ${VOLSYNC_SECRET_STORE:=onepassword-connect}
  target:
    name: ${APP}-restic
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: ${VOLSYNC_REPOSITORY}
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
        AWS_DEFAULT_REGION: ${VOLSYNC_AWS_REGION:=us-east-1}
  dataFrom:
    - extract:
        key: ${VOLSYNC_SECRET_KEY:=volsync-garage}
