---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ${APP}
spec:
  sourcePVC: ${VOLSYNC_SOURCE_PVC:=${APP}}
  trigger:
    schedule: "${VOLSYNC_SCHEDULE:=17 */6 * * *}"
  restic:
    repository: ${APP}-restic
    copyMethod: ${VOLSYNC_COPY_METHOD:=Snapshot}
    storageClassName: ${VOLSYNC_STORAGE_CLASS:=longhorn}
    volumeSnapshotClassName: ${VOLSYNC_VOLUME_SNAPSHOT_CLASS:=longhorn}
    cacheStorageClassName: ${VOLSYNC_CACHE_STORAGE_CLASS:=longhorn}
    moverAffinity:
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/name: ${VOLSYNC_MOVER_APP_NAME}
                app.kubernetes.io/instance: ${VOLSYNC_MOVER_APP_INSTANCE}
            topologyKey: kubernetes.io/hostname
    pruneIntervalDays: ${VOLSYNC_PRUNE_INTERVAL_DAYS:=7}
    cacheCapacity: ${VOLSYNC_CACHE_CAPACITY:=1Gi}
    retain:
      hourly: ${VOLSYNC_RETAIN_HOURLY:=4}
      daily: ${VOLSYNC_RETAIN_DAILY:=7}
      weekly: ${VOLSYNC_RETAIN_WEEKLY:=4}
      monthly: ${VOLSYNC_RETAIN_MONTHLY:=3}
