---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: speedtest-tracker
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: speedtest-tracker-secret
    template:
      engineVersion: v2
      data:
        # App
        APP_KEY: '{{ .app_key }}'
  dataFrom:
    - extract:
        key: speedtest-tracker

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: speedtest-tracker-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: speedtest-tracker-db-secret
    template:
      engineVersion: v2
      data:
        DB_DATABASE: speedtest_tracker
        DB_HOST: postgres17.databases.svc.cluster.local
        DB_USERNAME: '{{ .POSTGRES_SUPER_USER }}'
        DB_PASSWORD: '{{ .POSTGRES_SUPER_PASS }}'
        DB_PORT: '5432'
        DB_CONNECTION: 'pgsql'

  dataFrom:
    - extract:
        key: cloudnative-pg
