---
apiVersion: kopiur.home-operations.com/v1alpha1
kind: Restore
metadata:
  name: ${APP}-scratch-restore
spec:
  source:
    fromPolicy:
      name: ${APP}
      offset: ${KOPIUR_RESTORE_OFFSET:=0}
  target:
    pvc:
      name: ${KOPIUR_RESTORE_PVC:=${APP}-kopiur-scratch}
      storageClassName: ${KOPIUR_STORAGE_CLASS:=miroir-replicated}
      capacity: ${KOPIUR_RESTORE_CAPACITY}
      accessModes:
        - ReadWriteOnce
  policy:
    onMissingSnapshot: Fail
    waitTimeout: 5m
  options:
    enableFileDeletion: true
    ignorePermissionErrors: false
    skipOwners: false
    skipPermissions: false
    skipTimes: false
  mover:
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
      capabilities:
        add:
          - CHOWN
          - DAC_OVERRIDE
          - FOWNER
          - FSETID
    privilegedMode: true
