---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name toolhive-sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      data:
        SONARR_API_KEY: "{{ .SONARR__API_KEY }}"
  dataFrom:
    - extract:
        key: sonarr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &groupName toolhive-radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *groupName
    template:
      data:
        RADARR_API_KEY: "{{ .RADARR__API_KEY }}"
  dataFrom:
    - extract:
        key: radarr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &prowlarrName toolhive-prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *prowlarrName
    template:
      data:
        PROWLARR_API_KEY: "{{ .PROWLARR__API_KEY }}"
  dataFrom:
    - extract:
        key: prowlarr
