---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sure
  namespace: flux-system
spec:
  components:
    - ../../../../components/kopiur
    - ../../../../components/volsync
  targetNamespace: *app
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kopiur-repository-sure
      namespace: flux-system
    - name: volsync
      namespace: flux-system
  path: "./kubernetes/misc/sure/sure/app"
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: sure
      KOPIUR_SOURCE_PVC: sure-kopiur-replacement
      KOPIUR_SCHEDULE: "37 */6 * * *"
      KOPIUR_SUSPEND: "false"
      VOLSYNC_REPOSITORY: s3:http://garage.garage.svc.cluster.local:3900/volsync/sure/sure
      VOLSYNC_SOURCE_PVC: sure-kopiur-replacement
      VOLSYNC_STORAGE_CLASS: miroir-replicated
      VOLSYNC_VOLUME_SNAPSHOT_CLASS: miroir-snap
      VOLSYNC_CACHE_STORAGE_CLASS: miroir-ephemeral
      VOLSYNC_MOVER_APP_NAME: sure
      VOLSYNC_MOVER_APP_INSTANCE: sure
      VOLSYNC_SCHEDULE: "37 */6 * * *"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
