---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config-miroir
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir-replicated
  resources:
    requests:
      storage: 1Gi
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: seerr-config-miroir-restore
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seerr-config-cache-miroir
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir-replicated
  resources:
    requests:
      storage: 15Gi
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: seerr-config-cache-miroir-restore
