---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ./homepage/namespace.yaml
- ./homepage/install.yaml
- ./grafana/operator/install.yaml
- ./grafana/instance/install.yaml
- ./kube-prometheus-stack/install.yaml
- ./victoria-logs/install.yaml
- ./victoria-logs/collector/install.yaml
- ./grafana/mcp/install.yaml
- ./gatus/install.yaml
- ./karma/install.yaml
- ./kromgo/install.yaml
- ./promxy/install.yaml
- ./prometheus-adapter/install.yaml
- ./silence-operator/install.yaml
