---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app zerobyte
  namespace: flux-system
spec:
  components:
    - ../../../../components/kopiur
  targetNamespace: zerobyte
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kopiur-repository-zerobyte
      namespace: flux-system
  path: "./kubernetes/misc/zerobyte/zerobyte/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: zerobyte
      KOPIUR_SOURCE_PVC: zerobyte-kopiur-replacement
      KOPIUR_SCHEDULE: "13 */6 * * *"
      KOPIUR_SUSPEND: "false"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
