---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-miroir
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: miroir-replicated
  resources:
    requests:
      storage: 5Gi
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: tandoor-miroir-restore
