---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: audiobookshelf
  namespace: flux-system
spec:
  components:
    - ../../../components/volsync
  targetNamespace: books
  commonMetadata:
    labels:
      app.kubernetes.io/name: audiobookshelf
  dependsOn:
    - name: volsync
      namespace: flux-system
  path: "./kubernetes/books/audiobookshelf/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: audiobookshelf-config
      VOLSYNC_REPOSITORY: s3:http://garage.garage.svc.cluster.local:3900/volsync/books/audiobookshelf-config
      VOLSYNC_SOURCE_PVC: audiobookshelf-config
      VOLSYNC_MOVER_APP_NAME: audiobookshelf
      VOLSYNC_MOVER_APP_INSTANCE: audiobookshelf
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
