---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recyclarr-miroir
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir-replicated
  resources:
    requests:
      storage: 1Gi
