---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app suwayomi
  namespace: flux-system
spec:
  components:
    - ../../../components/kopiur
  targetNamespace: books
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: kopiur-repository-books
      namespace: flux-system
  path: "./kubernetes/books/suwayomi/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: suwayomi
      KOPIUR_SOURCE_PVC: suwayomi-kopiur-replacement
      KOPIUR_SCHEDULE: "58 */6 * * *"
      KOPIUR_SUSPEND: "false"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
