---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
spec:
  interval: 15m
  chart:
    spec:
      chart: plugin-barman-cloud
      version: 0.8.1
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
        namespace: flux-system
      interval: 15m
  # The plugin must run in the operator's namespace, which the operator
  # scans for plugin Services.
  dependsOn:
    - name: cloudnative-pg
  maxHistory: 2
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: false
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    crds:
      create: true
