---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-secret
    template:
      data:
        SONARR__AUTH__APIKEY: "{{ .SONARR__API_KEY }}"
  dataFrom:
    - extract:
        key: sonarr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-db-secret
    template:
      engineVersion: v2
      data:
        SONARR__POSTGRES__MAINDB: sonarr_main
        SONARR__POSTGRES__LOGDB: sonarr_log
        SONARR__POSTGRES__HOST: postgres17.databases.svc.cluster.local
        SONARR__POSTGRES__USER: '{{ .POSTGRES_SUPER_USER }}'
        SONARR__POSTGRES__PASSWORD: '{{ .POSTGRES_SUPER_PASS }}'
        SONARR__POSTGRES__PORT: '5432'
  dataFrom:
    - extract:
        key: cloudnative-pg