---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-secret
    template:
      data:
        SONARR__AUTH__APIKEY: "{{ .SONARR__API_KEY }}"
  dataFrom:
    - extract:
        key: sonarr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sonarr-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-db-secret
    template:
      engineVersion: v2
      data:
        SONARR__POSTGRES__MAINDB: &maindb sonarr_main
        SONARR__POSTGRES__LOGDB: sonarr_log
        SONARR__POSTGRES__HOST: postgres17-rw.databases.svc.cluster.local
        SONARR__POSTGRES__USER: &dbuser sonarr
        SONARR__POSTGRES__PASSWORD: &dbpass '{{ .SONARR_POSTGRES_PASSWORD }}'
        SONARR__POSTGRES__PORT: '5432'

        # Postgres init
        INIT_POSTGRES_DBNAME: *maindb
        INIT_POSTGRES_HOST: postgres17-rw.databases.svc.cluster.local
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: sonarr
