---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name opencode
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    template:
      data:
        OPENCODE_SERVER_PASSWORD: "{{ .OPENCODE_SERVER_PASSWORD }}"
        OPENROUTER_API_KEY: "{{ .OPENROUTER_API_KEY }}"
  dataFrom:
    - extract:
        key: opencode
    - extract:
        key: ai-api-keys
