---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-secret
    template:
      data:
        RADARR__AUTH__APIKEY: "{{ .RADARR__API_KEY }}"
  dataFrom:
    - extract:
        key: radarr
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr-db
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-db-secret
    template:
      engineVersion: v2
      data:
        RADARR__POSTGRES__MAINDB: radarr_main
        RADARR__POSTGRES__LOGDB: radarr_log
        RADARR__POSTGRES__HOST: postgres17.databases.svc.cluster.local
        RADARR__POSTGRES__USER: '{{ .POSTGRES_SUPER_USER }}'
        RADARR__POSTGRES__PASSWORD: '{{ .POSTGRES_SUPER_PASS }}'
        RADARR__POSTGRES__PORT: '5432'
  dataFrom:
    - extract:
        key: cloudnative-pg