---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config-kopiur-replacement
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir-replicated
  resources:
    requests:
      storage: 5Gi
