---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./all-minilm-l6-v2
  - ./lfm2-230m
  - ./ornith-1-0-35b
