---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bookorbit
spec:
  target:
    name: bookorbit-secret
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        POSTGRES_PASSWORD: "{{ .BOOKORBIT_POSTGRES_PASSWORD }}"
        JWT_SECRET: "{{ .BOOKORBIT_JWT_SECRET }}"
        SETUP_BOOTSTRAP_TOKEN: "{{ .BOOKORBIT_SETUP_BOOTSTRAP_TOKEN }}"
        INIT_POSTGRES_DBNAME: bookorbit
        INIT_POSTGRES_HOST: pgvector17-rw.databases.svc.cluster.local
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: bookorbit
        INIT_POSTGRES_PASS: "{{ .BOOKORBIT_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: bookorbit
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword-connect
    - extract:
        key: cloudnative-pg
      sourceRef:
        storeRef:
          kind: ClusterSecretStore
          name: onepassword-connect
