---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sure
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sure-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        SECRET_KEY_BASE: "{{ .SURE_SECRET_KEY_BASE }}"
        OIDC_CLIENT_ID: "{{ .SURE_OIDC_CLIENT_ID }}"
        OIDC_CLIENT_SECRET: "{{ .SURE_OIDC_CLIENT_SECRET }}"

        POSTGRES_DB: &dbname sure
        POSTGRES_USER: &dbuser sure
        POSTGRES_PASSWORD: &dbpass "{{ .SURE_POSTGRES_PASSWORD }}"
        DB_HOST: postgres17-rw.databases.svc.cluster.local
        DB_PORT: "5432"

        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: postgres17-rw.databases.svc.cluster.local
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass

        REDIS_URL: redis://dragonfly.databases.svc.cluster.local:6379/1
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: sure
