---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sure
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sure-redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sure-miroir
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir-replicated
  resources:
    requests:
      storage: 5Gi
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: sure-miroir-restore
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sure-redis-miroir
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir-replicated
  resources:
    requests:
      storage: 1Gi
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: sure-redis-miroir-restore
