---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app komga
  namespace: flux-system
spec:
  components:
    - ../../../components/volsync
  targetNamespace: manga
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: volsync
      namespace: flux-system
  path: "./kubernetes/manga/komga/app"
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: komga
      VOLSYNC_REPOSITORY: s3:http://garage.garage.svc.cluster.local:3900/volsync/manga/komga
      VOLSYNC_SOURCE_PVC: komga
      VOLSYNC_MOVER_APP_NAME: komga
      VOLSYNC_MOVER_APP_INSTANCE: komga
      VOLSYNC_SCHEDULE: "52 */6 * * *"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
