---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qwen3-6-35b-a3b
spec:
  parentRefs:
    - name: envoy-internal
      namespace: networking
      sectionName: https
  hostnames:
    - "qwen.${LOCAL_DOMAIN}"
  rules:
    - backendRefs:
        - name: qwen3-6-35b-a3b
          port: 8080
