---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shadow-cloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: shadow-cloud-secret
    template:
      data:
        AUTH_SECRET: "{{ .AUTH_SECRET }}"
        BOT_API_TOKEN: "{{ .BOT_API_TOKEN }}"
        SHADOW_CLOUD_BOT_NOTIFY_SECRET: "{{ .SHADOW_CLOUD_BOT_NOTIFY_SECRET }}"
        AUTH_DISCORD_ID: "{{ .AUTH_DISCORD_ID }}"
        AUTH_DISCORD_SECRET: "{{ .AUTH_DISCORD_SECRET }}"
        DISCORD_BOT_TOKEN: "{{ .DISCORD_BOT_TOKEN }}"
        SHADOW_OVERRIDE_DISCORD_ROLE_ID: "{{ .SHADOW_OVERRIDE_DISCORD_ROLE_ID }}"
  dataFrom:
    - extract:
        key: shadow-cloud