---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/mcpserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPServer
metadata:
  name: talos-mcp
spec:
  # renovate: depName=registry.erwanleboucher.dev/eleboucher/talos-mcp
  image: registry.erwanleboucher.dev/eleboucher/talos-mcp@sha256:571d9d6f77221bc7420ac3af44db94dc587c1c13fa4281ba1e6cc8dfbf27381a
  transport: streamable-http
  mcpPort: 8080
  groupRef:
    name: mcp-tools
  permissionProfile:
    type: builtin
    name: network
  env:
    - name: TALOS_MCP_TRANSPORT
      value: http
    - name: TALOS_MCP_HTTP_ADDR
      value: ":8080"
  podTemplateSpec:
    spec:
      containers:
        - name: mcp
          volumeMounts:
            - name: talosconfig
              mountPath: /var/run/secrets/talos.dev
              readOnly: true
      volumes:
        - name: talosconfig
          secret:
            secretName: talos-mcp-talosconfig
            defaultMode: 0400
