---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sonarr
  namespace: flux-system
spec:
  components:
    - ../../../components/kopiur
    - ../../../components/volsync
  targetNamespace: home-media
  commonMetadata:
    labels:
      app.kubernetes.io/name: sonarr
  dependsOn:
    - name: kopiur-repository-home-media
      namespace: flux-system
    - name: volsync
      namespace: flux-system
  path: "./kubernetes/media/sonarr/app"
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: sonarr-config
      KOPIUR_SOURCE_PVC: sonarr-config-miroir
      KOPIUR_SCHEDULE: "40 */6 * * *"
      VOLSYNC_REPOSITORY: s3:http://garage.garage.svc.cluster.local:3900/volsync/home-media/sonarr-config
      VOLSYNC_SOURCE_PVC: sonarr-config-miroir
      VOLSYNC_STORAGE_CLASS: miroir-replicated
      VOLSYNC_VOLUME_SNAPSHOT_CLASS: miroir-snap
      VOLSYNC_CACHE_STORAGE_CLASS: miroir-ephemeral
      VOLSYNC_MOVER_APP_NAME: sonarr
      VOLSYNC_MOVER_APP_INSTANCE: sonarr
      VOLSYNC_SCHEDULE: "40 */6 * * *"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
