---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: libation
  namespace: flux-system
spec:
  components:
    - ../../../components/volsync
  targetNamespace: books
  commonMetadata:
    labels:
      app.kubernetes.io/name: libation
  dependsOn:
    - name: volsync
      namespace: flux-system
  path: ./kubernetes/books/libation/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: libation-config
      VOLSYNC_REPOSITORY: s3:http://garage.garage.svc.cluster.local:3900/volsync/books/libation-config
      VOLSYNC_SOURCE_PVC: libation-config
      VOLSYNC_MOVER_APP_NAME: libation
      VOLSYNC_MOVER_APP_INSTANCE: libation
      VOLSYNC_SCHEDULE: "27 */6 * * *"
      VOLSYNC_COPY_METHOD: Direct
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
