---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ./agentmemory/install.yaml
- ./hermes/install.yaml
- ./llama-embed/install.yaml
- ./openwebui/install.yaml
- ./searxng/install.yaml
- ./toolhive/crds/install.yaml
- ./toolhive/operator/install.yaml
- ./toolhive/config/install.yaml
