---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name firecrawl
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: firecrawl-secret
    template:
      engineVersion: v2
      data:
        BULL_AUTH_KEY: "{{ .BULL_AUTH_KEY }}"
        OPENAI_API_KEY: "{{ .OPENROUTER_API_KEY }}"
        RABBITMQ_DEFAULT_USER: firecrawl
        RABBITMQ_DEFAULT_PASS: "{{ .FIRECRAWL_RABBITMQ_PASSWORD }}"
        NUQ_RABBITMQ_URL: "amqp://firecrawl:{{ .FIRECRAWL_RABBITMQ_PASSWORD | urlquery }}@firecrawl-rabbitmq.ai.svc.cluster.local:5672"
        NUQ_DATABASE_URL: "postgresql://firecrawl:{{ .FIRECRAWL_POSTGRES_PASSWORD | urlquery }}@postgres17-rw.databases.svc.cluster.local:5432/firecrawl"
        NUQ_DATABASE_URL_LISTEN: "postgresql://firecrawl:{{ .FIRECRAWL_POSTGRES_PASSWORD | urlquery }}@postgres17-rw.databases.svc.cluster.local:5432/firecrawl"

        # Postgres init
        INIT_POSTGRES_DBNAME: firecrawl
        INIT_POSTGRES_HOST: postgres17-rw.databases.svc.cluster.local
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        INIT_POSTGRES_USER: firecrawl
        INIT_POSTGRES_PASS: "{{ .FIRECRAWL_POSTGRES_PASSWORD }}"
  dataFrom:
    - extract:
        key: firecrawl
    - extract:
        key: cloudnative-pg
    - extract:
        key: ai-api-keys
