---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cleanuparr-config-miroir
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: miroir-replicated
  resources:
    requests:
      storage: 10Gi
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: cleanuparr-config-miroir-restore
