---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: jellyseerr
  namespace: flux-system
spec:
  components:
    - ../../../components/kopiur
  targetNamespace: home-media
  commonMetadata:
    labels:
      app.kubernetes.io/name: jellyseerr
  dependsOn:
    - name: kopiur-repository-home-media
      namespace: flux-system
  path: "./kubernetes/media/jellyseer/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: seerr-config
      KOPIUR_SOURCE_PVC: seerr-config-kopiur-replacement
      KOPIUR_SCHEDULE: "10 */6 * * *"
      KOPIUR_SUSPEND: "false"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seerr-config-cache-kopiur
  namespace: flux-system
spec:
  targetNamespace: home-media
  dependsOn:
    - name: jellyseerr
    - name: kopiur-repository-home-media
      namespace: flux-system
  path: "./kubernetes/components/kopiur-standalone"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: seerr-config-cache
      KOPIUR_SOURCE_PVC: seerr-config-cache-miroir
      KOPIUR_SCHEDULE: "31 */6 * * *"
      KOPIUR_SUSPEND: "true"
