---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc-miroir
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir-replicated
  resources:
    requests:
      storage: 10Gi
