---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./restores.yaml
patches:
  - target:
      kind: ReplicationDestination
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          volsync.backube/privileged-movers: "true"
