---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zerobyte
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zerobyte-secret
    template:
      engineVersion: v2
      data:
        app-secret: '{{ .app_secret }}'
  dataFrom:
    - extract:
        key: zerobyte

---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret  
metadata:
  name: rclone-configmap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zerobyte-rclone-config
    template:
      engineVersion: v2
      data:
        rclone.conf: | 
          [garage]
          type = s3
          provider = Other
          env_auth = false
          access_key_id = {{ .access_key_id }}
          secret_access_key = {{ .secret_access_key }}
          endpoint = http://garage.garage.svc.cluster.local:3900
          region = us-east-1
          acl = private
          disable_http2 = true
          no_check_bucket = true
  dataFrom:
    - extract:
        key: rclone