---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zerobyte
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zerobyte-secret
    template:
      engineVersion: v2
      data:
        app-secret: '{{ .app_secret }}'
  dataFrom:
    - extract:
        key: zerobyte
