---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app hermes
  namespace: flux-system
spec:
  components:
    - ../../../components/volsync
  dependsOn:
    - name: agentmemory
    - name: grafana-mcp
    - name: llama-embed
    - name: toolhive-config
    - name: volsync
      namespace: flux-system
  path: "./kubernetes/ai/hermes/app"
  targetNamespace: ai
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 10m
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      APP: hermes
      VOLSYNC_REPOSITORY: s3:http://garage.garage.svc.cluster.local:3900/volsync/ai/hermes
      VOLSYNC_SOURCE_PVC: hermes
      VOLSYNC_MOVER_APP_NAME: hermes
      VOLSYNC_MOVER_APP_INSTANCE: hermes
      VOLSYNC_SCHEDULE: "9 */6 * * *"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
