---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: victoria-logs
    namespace: flux-system
  values:
    dashboards:
      enabled: true
    fullnameOverride: victoria-logs
    server:
      persistentVolume:
        enabled: true
        storageClassName: longhorn
        size: 20Gi
      retentionPeriod: 14d
      serviceMonitor:
        enabled: true
      route:
        enabled: true
        hostnames:
          - victoria-logs.${LOCAL_DOMAIN}
        parentRefs:
          - name: envoy-internal
            namespace: networking
            sectionName: https
        extraRules:
          - matches:
              - path:
                  type: Exact
                  value: /
            filters:
              - type: RequestRedirect
                requestRedirect:
                  path:
                    type: ReplaceFullPath
                    replaceFullPath: /select/vmui/
                  statusCode: 302
