---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app agentmemory
  namespace: flux-system
spec:
  components:
    - ../../../components/volsync
  dependsOn:
    - name: llama
    - name: volsync
      namespace: flux-system
  path: "./kubernetes/ai/agentmemory/app"
  targetNamespace: ai
  prune: true
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      APP: agentmemory
      VOLSYNC_REPOSITORY: s3:http://garage.garage.svc.cluster.local:3900/volsync/ai/agentmemory
      VOLSYNC_SOURCE_PVC: agentmemory
      VOLSYNC_MOVER_APP_NAME: agentmemory
      VOLSYNC_MOVER_APP_INSTANCE: agentmemory
      VOLSYNC_SCHEDULE: "3 */6 * * *"
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
        optional: false
