---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-kopiur-replacement
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir-replicated
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seedboxapi-config-kopiur-replacement
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir-replicated
  resources:
    requests:
      storage: 1Gi
