---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-miroir
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir-replicated
  resources:
    requests:
      storage: 1Gi
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: qbittorrent-config-miroir-restore
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: seedboxapi-config-miroir
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: miroir-replicated
  resources:
    requests:
      storage: 1Gi
  dataSourceRef:
    apiGroup: volsync.backube
    kind: ReplicationDestination
    name: seedboxapi-config-miroir-restore
